url: "https://nachoabad.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
title: "Nacho's Blog"

plugins:
  - jekyll-postcss

postcss:
  cache: false
